import express, { Request, Response, Router } from 'express'
import { config } from '../config'

const router = Router()

interface TextToSpeechRequest {
  text: string
  voiceId?: string
}

interface TextToSpeechResponse {
  success: boolean
  audioUrl?: string
  provider: string
  message?: string
}

// Synthesize speech using browser Web Audio API
// In Phase 1, we provide a simple text-to-speech solution
router.post('/synthesize', async (req: Request, res: Response) => {
  try {
    const { text } = req.body as TextToSpeechRequest

    if (!text) {
      return res.status(400).json({
        success: false,
        message: 'Text is required',
        provider: config.voice.provider,
      })
    }

    // Phase 1: Return a simple spoken text marker
    // The frontend will use Web Speech API or browser TTS
    // Later phases will connect to Piper (local) or ElevenLabs (server-side)

    const response: TextToSpeechResponse = {
      success: true,
      provider: config.voice.provider,
      message: `Ready to speak: "${text}"`,
      audioUrl: undefined, // Will be generated by browser in Phase 1
    }

    res.json(response)
  } catch (error) {
    res.status(500).json({
      success: false,
      provider: config.voice.provider,
      message: error instanceof Error ? error.message : 'Unknown error',
    })
  }
})

// Get voice configuration
router.get('/config', (req: Request, res: Response) => {
  res.json({
    provider: config.voice.provider,
    voiceId: config.voice.elevenLabsVoiceId,
    capabilities: ['text-to-speech', 'speech-recognition-ready'],
    note: 'ElevenLabs and Piper will be connected in later phases. Phase 1 uses browser Web Speech API.',
  })
})

export default router
